name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd JetsBe
          git pull
          mvn -B clean package -DskipTests
          sudo systemctl stop tomcat.service
          sudo rm -rf /opt/tomcat/webapps/jetsbe*
          sudo cp /home/deploy/JetsBe/target/JetsBe-0.0.1-SNAPSHOT.war /opt/tomcat/webapps/jetsbe.war
          sudo chown tomcat. /opt/tomcat/webapps/jetsbe.war
          sudo systemctl start tomcat.service
